name: Build and Push netease_music_api1 (Multi-Arch, GHCR Only)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'netease_music_api/**'
      - '.github/workflows/netease_music_api-builder.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Get lowercase repo owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Extract VERSION from config
        id: extract_version
        run: |
          ADDON_DIR="netease_music_api"
          CONFIG_PATH="${ADDON_DIR}/config.json"

          if [[ -f "$CONFIG_PATH" ]]; then
            VERSION=$(yq e -r '.version' "$CONFIG_PATH")
          else
            echo "❌ ERROR: $CONFIG_PATH not found!"
            exit 1
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "💡 VERSION=$VERSION"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: netease_music_api
          file: netease_music_api/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER_LC }}/netease_music_api:${{ env.VERSION }}
